# Generated by Django 3.2.12 on 2022-03-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ques',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ques',
            name='QuizUser',
        ),
        migrations.AddField(
            model_name='ques',
            name='quiz_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='friendship.quizuser'),
        ),
        migrations.AlterField(
            model_name='ques',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
